name: Sync JSON
on:
  schedule:
    - cron: '*/5 * * * *'   # Chạy 5 phút 1 lần
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4 playwright
      - run: playwright install chromium
      - run: python sync.py
      - run: python scrape_buncha.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hoiquan.json buncha.json
          git diff --staged --quiet || git commit -m "sync"
          git push
